"""'Init'

Revision ID: 5dfb846257d3
Revises: 
Create Date: 2024-01-17 20:12:06.043869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dfb846257d3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('groups_id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('groups_id')
    )
    op.create_table('teachers',
    sa.Column('teachers_id', sa.Integer(), nullable=False),
    sa.Column('teachers_name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('teachers_id')
    )
    op.create_table('disciplines',
    sa.Column('disciplines_id', sa.Integer(), nullable=False),
    sa.Column('disciplines_name', sa.String(length=30), nullable=False),
    sa.Column('teachers_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['teachers_id'], ['teachers.teachers_id'], ),
    sa.PrimaryKeyConstraint('disciplines_id')
    )
    op.create_table('students',
    sa.Column('students_id', sa.Integer(), nullable=False),
    sa.Column('students_name', sa.String(length=40), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.groups_id'], ),
    sa.PrimaryKeyConstraint('students_id')
    )
    op.create_table('grades',
    sa.Column('grades_id', sa.Integer(), nullable=False),
    sa.Column('grades', sa.Integer(), nullable=False),
    sa.Column('date_grade', sa.DateTime(), nullable=False),
    sa.Column('students_id', sa.Integer(), nullable=False),
    sa.Column('disciplines_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['disciplines_id'], ['disciplines.disciplines_id'], ),
    sa.ForeignKeyConstraint(['students_id'], ['students.students_id'], ),
    sa.PrimaryKeyConstraint('grades_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grades')
    op.drop_table('students')
    op.drop_table('disciplines')
    op.drop_table('teachers')
    op.drop_table('groups')
    # ### end Alembic commands ###
